=== AlexTuli/parser/src/main/resources/xml/product-list.dtd
<!DOCTYPE categories [
        <!ELEMENT categories (category+)>
        <!ELEMENT category (name, subCategory+)>
        <!ELEMENT subCategory (name, product+)>
        <!ELEMENT product (name, provider, model, dateOfIssue, notInStock, color, price)>

        <!ELEMENT name (#PCDATA)>
        <!ELEMENT provider (#PCDATA)>
        <!ELEMENT model (#PCDATA)>
        <!ELEMENT dateOfIssue (#PCDATA)>
        <!ELEMENT notInStock (&true;|&false;) >
        <!ELEMENT color (#PCDATA) >
        <!ELEMENT price (#PCDATA)>

        <!ENTITY true "true">
        <!ENTITY false "false">
        ]>

=== AlexTuli/parser/src/main/resources/xml/my-list.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--<!DOCTYPE categories SYSTEM "product-list.dtd">-->
<categories
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="product-list.xsd">
    <category>
      <name>It is a category</name>
      <subCategory>
        <name>It is a sub category</name>
        <product>
            <name>SUPER PRODUCT</name>
            <provider>PROVIDER-DUMBRIDER</provider>
            <model>hh134</model>
            <dateOfIssue>10/15/2015</dateOfIssue>
            <notInStock>true</notInStock>
            <color>blue</color>
            <price>123.45</price>
        </product>
    </subCategory>
     </category>
</categories>
